### ISSUE TITLE
npm installation problem

### ISSUE THREAD

**Issue by tfoxy** [vitalets/sinon-chrome#3]
Version 0.1.1 from npmjs is broken. It throws the following error when it is executed:

````sh
module.js:338
    throw err;
          ^
Error: Cannot find module './chrome-event'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /path/to/package/node_modules/sinon-chrome/chrome.js:91:23
    at Object.<anonymous> (/path/to/package/node_modules/sinon-chrome/chrome.js:865:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
````

The package.json is different from the one here in github. The main property value is "chrome.js" instead of "src/chrome.js". This file exists. But, as the error shows, it doesn't find the chrome-event module in the root folder. The chrome-event module is inside the src folder.

Version 0.1.0 doesn't have this problem.

**Comment by vitalets** [comment]
fixed in 0.1.2
thanks!
